logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://jalgoarena-eureka-koscinsa.herokuapp.com/eureka/}

server:
  port: ${PORT:5002}
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME:jalgoarena-problems-koscinsa}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
